
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'); let shots=0, dragging=false, mouse={x:0,y:0};
const pockets=[[60,60],[550,50],[1040,60],[60,580],[550,590],[1040,580]]; let cue, balls=[];
function reset(){ cue={x:240,y:320,vx:0,vy:0,r:14,color:'#fff'}; balls=[]; const colors=['#d7a657','#d96','#6cf','#f55','#9f6','#f6f']; for(let i=0;i<6;i++) balls.push({x:760+(i%3)*34,y:320+(i-2.5)*34,vx:0,vy:0,r:14,color:colors[i],alive:true}); shots=0; upd(); draw(); msg('Clear the rack with as few shots as possible.'); }
function upd(){ document.getElementById('shots').textContent=shots; document.getElementById('left').textContent=balls.filter(b=>b.alive).length; document.getElementById('state').textContent=balls.every(b=>!b.alive)?'Cleared':'Live'; }
function msg(t){document.getElementById('msg').textContent=t}
function reflect(b){ if(b.x<b.r+70||b.x>canvas.width-70-b.r) b.vx*=-1; if(b.y<b.r+70||b.y>canvas.height-70-b.r) b.vy*=-1; b.x=Math.max(70+b.r,Math.min(canvas.width-70-b.r,b.x)); b.y=Math.max(70+b.r,Math.min(canvas.height-70-b.r,b.y)); }
function step(){ const all=[cue,...balls.filter(b=>b.alive)]; all.forEach(b=>{ b.x+=b.vx; b.y+=b.vy; b.vx*=0.988; b.vy*=0.988; if(Math.abs(b.vx)<.02)b.vx=0; if(Math.abs(b.vy)<.02)b.vy=0; reflect(b); pockets.forEach(([px,py])=>{ if((b.x-px)**2+(b.y-py)**2<28**2){ if(b===cue){ cue.x=240; cue.y=320; cue.vx=cue.vy=0; msg('Scratch. Cue ball returned.'); } else { b.alive=false; msg('Ball down.'); } } });});
 for(let i=0;i<all.length;i++) for(let j=i+1;j<all.length;j++){ const a=all[i],b=all[j], dx=b.x-a.x, dy=b.y-a.y, dist=Math.hypot(dx,dy), min=a.r+b.r; if(dist&&dist<min){ const nx=dx/dist, ny=dy/dist; const p=(a.vx*nx+a.vy*ny - b.vx*nx-b.vy*ny); a.vx-=p*nx; a.vy-=p*ny; b.vx+=p*nx; b.vy+=p*ny; const overlap=min-dist; a.x-=nx*overlap/2; a.y-=ny*overlap/2; b.x+=nx*overlap/2; b.y+=ny*overlap/2; } }
 upd(); draw(); requestAnimationFrame(step); }
function draw(){ const g=ctx.createLinearGradient(0,0,0,canvas.height); g.addColorStop(0,'#060606'); g.addColorStop(1,'#0a0a0a'); ctx.fillStyle=g; ctx.fillRect(0,0,canvas.width,canvas.height); ctx.fillStyle='#2a1b05'; ctx.fillRect(30,30,1040,580); const felt=ctx.createLinearGradient(70,70,1030,570); felt.addColorStop(0,'#062615'); felt.addColorStop(1,'#04160d'); ctx.fillStyle=felt; ctx.fillRect(70,70,960,500); ctx.strokeStyle='rgba(215,166,87,.55)'; ctx.lineWidth=4; ctx.strokeRect(70,70,960,500); pockets.forEach(([x,y])=>{ ctx.fillStyle='#000'; ctx.beginPath(); ctx.arc(x,y,28,0,Math.PI*2); ctx.fill();}); if(dragging){ ctx.strokeStyle='rgba(244,209,135,.95)'; ctx.lineWidth=3; ctx.beginPath(); ctx.moveTo(cue.x,cue.y); ctx.lineTo(mouse.x,mouse.y); ctx.stroke(); }
 [cue,...balls.filter(b=>b.alive)].forEach(b=>{ ctx.fillStyle=b.color; ctx.beginPath(); ctx.arc(b.x,b.y,b.r,0,Math.PI*2); ctx.fill(); ctx.strokeStyle='rgba(255,255,255,.22)'; ctx.stroke(); }); }
canvas.onpointerdown=e=>{ const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*(canvas.width/r.width),y=(e.clientY-r.top)*(canvas.height/r.height); if(Math.hypot(x-cue.x,y-cue.y)<28 && cue.vx===0&&cue.vy===0){ dragging=true; mouse={x,y}; }}; canvas.onpointermove=e=>{ if(!dragging)return; const r=canvas.getBoundingClientRect(); mouse={x:(e.clientX-r.left)*(canvas.width/r.width),y:(e.clientY-r.top)*(canvas.height/r.height)}; draw(); }; canvas.onpointerup=()=>{ if(!dragging)return; dragging=false; const power=Math.min(18,Math.hypot(cue.x-mouse.x,cue.y-mouse.y)/8); const ang=Math.atan2(cue.y-mouse.y,cue.x-mouse.x); cue.vx=Math.cos(ang)*power; cue.vy=Math.sin(ang)*power; shots++; upd(); msg('Shot taken.'); };
document.getElementById('reset').onclick=reset; reset(); requestAnimationFrame(step);
