
(()=>{
const suits=['♠','♥','♦','♣'], ranks=['A','2','3','4','5','6','7','8','9','10','J','Q','K'], val=Object.fromEntries(ranks.map((r,i)=>[r,i+1]));
let deck=[],discard=[],hand=[],bot=[],creditsVal=1000,betVal=25,phase='ready',selected=null;
function mk(){deck=[];for(const s of suits)for(const r of ranks)deck.push({r,s});deck.sort(()=>Math.random()-.5)}
function chtml(c,i){return `<button class="card ${c.s==='♥'||c.s==='♦'?'red':''} ${selected===i?'selected':''}" data-i="${i}">${c.r}<br>${c.s}</button>`}
function score(h){let best=0;let byRank={};h.forEach(c=>(byRank[c.r]??=[]).push(c));for(const r in byRank)if(byRank[r].length>=3)best+=byRank[r].length*10;for(const s of suits){let nums=h.filter(c=>c.s===s).map(c=>val[c.r]).sort((a,b)=>a-b);let run=1;for(let i=1;i<nums.length;i++){if(nums[i]===nums[i-1]+1){run++; if(run>=3)best=Math.max(best,run*12)}else if(nums[i]!==nums[i-1])run=1}}return best}
function botTurn(){bot.push(deck.pop()||discard.pop());bot.sort((a,b)=>val[a.r]-val[b.r]);let bi=0,low=99;bot.forEach((c,i)=>{let v=val[c.r];if(v<low){low=v;bi=i}});discard.push(bot.splice(bi,1)[0])}
function render(){credits.textContent=creditsVal;bet.textContent=betVal;mainScore.textContent=creditsVal;let top=discard[discard.length-1];playArea.innerHTML=`<div class="scorebox"><span>Deck: ${deck.length}</span><span>Discard: ${top?top.r+top.s:'—'}</span><span>Your meld score: ${score(hand)}</span><span>Bot meld score: ${score(bot)}</span></div>`+hand.map(chtml).join('');document.querySelectorAll('#playArea .card').forEach(b=>b.onclick=()=>{selected=+b.dataset.i;render()});actionBtn.textContent=phase==='ready'?'DEAL':phase==='draw'?'DRAW CARD':'DISCARD SELECTED';stateText.textContent=phase.toUpperCase()}
function deal(){if(creditsVal<betVal){result.textContent='NOT ENOUGH CREDITS';return}creditsVal-=betVal;mk();hand=deck.splice(0,10);bot=deck.splice(0,10);discard=[deck.pop()];phase='draw';selected=null;result.textContent='Draw, then discard. First to 50 meld points wins.';render()}
function action(){if(phase==='ready')return deal();if(phase==='draw'){hand.push(deck.pop()||discard.pop());phase='discard';result.textContent='Pick a card to discard.';return render()}if(phase==='discard'){if(selected===null){result.textContent='Select a card first.';return}discard.push(hand.splice(selected,1)[0]);selected=null;botTurn();let ps=score(hand),bs=score(bot);if(ps>=50||bs>=50||deck.length<2){let win=ps>=bs,pay=win?betVal*3:0;if(pay)creditsVal+=pay;result.textContent=win?'RUMMY WIN +'+pay:'BOT WINS HAND';phase='ready'}else{phase='draw';result.textContent='Your draw.'}render()}}
actionBtn.onclick=action;newBtn.onclick=()=>{phase='ready';hand=[];bot=[];discard=[];result.textContent='READY';render()};betUp.onclick=()=>{if(phase==='ready'&&betVal<500)betVal+=25;render()};betDown.onclick=()=>{if(phase==='ready'&&betVal>25)betVal-=25;render()};render();
})();
