
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'); let running=false, score=0, combo=0, time=30, targets=[], timerInt=null;
function reset(){ running=false; clearInterval(timerInt); score=0; combo=0; time=30; targets=[]; ui(); draw(); msg('Tap targets fast. Build a streak.'); }
function ui(){ document.getElementById('score').textContent=score; document.getElementById('combo').textContent=combo; document.getElementById('time').textContent=time; }
function msg(t){document.getElementById('msg').textContent=t}
function spawn(){ targets.push({x:80+Math.random()*840,y:80+Math.random()*460,r:20+Math.random()*18,life:45}); }
function draw(){ ctx.fillStyle='#060606'; ctx.fillRect(0,0,canvas.width,canvas.height); const g=ctx.createRadialGradient(500,120,10,500,120,520); g.addColorStop(0,'rgba(215,166,87,.12)'); g.addColorStop(1,'rgba(0,0,0,0)'); ctx.fillStyle=g; ctx.fillRect(0,0,canvas.width,canvas.height); ctx.fillStyle='#121212'; ctx.fillRect(130,70,740,480); ctx.strokeStyle='rgba(215,166,87,.35)'; ctx.lineWidth=4; ctx.strokeRect(130,70,740,480); targets.forEach(t=>{ ctx.beginPath(); ctx.arc(t.x,t.y,t.r,0,Math.PI*2); ctx.fillStyle='rgba(215,166,87,.18)'; ctx.fill(); ctx.beginPath(); ctx.arc(t.x,t.y,t.r*0.62,0,Math.PI*2); ctx.fillStyle='#e7c277'; ctx.fill(); ctx.beginPath(); ctx.arc(t.x,t.y,t.r*0.26,0,Math.PI*2); ctx.fillStyle='#291b08'; ctx.fill();}); }
function step(){ if(!running) return; if(Math.random()<0.07) spawn(); targets.forEach(t=>t.life--); targets=targets.filter(t=>t.life>0); if(targets.some(t=>t.life===1)){ combo=0; ui(); } draw(); requestAnimationFrame(step); }
function start(){ if(running) return; running=true; msg('Drill live.'); timerInt=setInterval(()=>{ time--; ui(); if(time<=0){ clearInterval(timerInt); running=false; msg('Time. Reset and run it back.'); } },1000); requestAnimationFrame(step); }
canvas.onclick=e=>{ const r=canvas.getBoundingClientRect(), x=(e.clientX-r.left)*(canvas.width/r.width), y=(e.clientY-r.top)*(canvas.height/r.height); let hit=false; targets=targets.filter(t=>{ const ok=((x-t.x)**2+(y-t.y)**2)<=t.r*t.r; if(ok){ hit=true; score += 10 + combo*2; combo++; } return !ok; }); if(!hit) combo=0; ui(); draw(); };
document.getElementById('start').onclick=start; document.getElementById('reset').onclick=reset; reset();
